name: deploy

on: [push]

jobs:
  build:
    name: build
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: cd code/easy-vietnamese-dashboard && git fetch origin && git merge origin/develop && yarn build